### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by shenberg** [elazarg/nakdimon#15]
Hi, can you clarify the license of Nakdimon?

Thanks!

**Comment by elazarg** [comment]
The model and code are MIT. The data is essentially fair use - I do not own
it. My part (e.g. dotting most modern Hebrew texts) is MIT as far as I'm
concerned.

Elazar

בתאריך יום ב׳, 6 במרץ 2023, 12:36, מאת Roee Shenberg ‏<
***@***.***>:

**Comment by shenberg** [comment]
Btw, [https://nakdimon.org](https://nakdimon.org) is not working at the moment because the nanobar javascript dependency is pointing to a domain that was not renewed. I think it's this file: https://github.com/jacoborus/nanobar/blob/master/nanobar.min.js

**Comment by elazarg** [comment]
Fixed. Thanks!
