### ISSUE TITLE
Create an installable pip package 

### ISSUE THREAD

**Issue by Gilthans** [elazarg/nakdimon#19]
Hello, and thanks for the great tool!
I was wondering if it has been considered to package this so it can be installed and used using `pip` or another package manager?

Would a PR be accepted creating such a process?

**Comment by elazarg** [comment]
I did not think it would be useful to users; if you think it is, then I would love to see a PR. Thanks!

**Comment by elazarg** [comment]
@Gilthans please review the current state of `master`. I intend to publish it on pip.

**Comment by Gilthans** [comment]
Can't say I'm an expert, but looks good to me!
Sorry, I never did get around to it

**Comment by elazarg** [comment]
You can simply `pip install` it now, but there's still the issue of packing the model.
