### ISSUE TITLE
Convert to onnx runtime model

### ISSUE THREAD

**Issue by thewh1teagle** [elazarg/nakdimon#26]
I would like to convert the H5 model to onnxruntime. 
Does the model requires special preprocessing / postprocessing or we can simply feed it with א-ת?

Because looking at https://github.com/elazarg/nakdimon/blob/master/nakdimon/predict.py#L38 seems like you have special logic there.

**Comment by elazarg** [comment]
I am not familiar with onnx, so I am not entirely sure I understand your question.
If you follow the code, you can see the preprocessing of the input - essentially chunking, replacing end-letters with normal ones, removing nikkud, and encoding into numbers.

I can share with you the JS code that is used for the online demo, if that would be helpful. It does the minimal processing needed for user input (but in JS).

**Comment by thewh1teagle** [comment]
> I am not familiar with onnx, so I am not entirely sure I understand your question.
> If you follow the code, you can see the preprocessing of the input - essentially chunking, replacing end-letters with normal ones, removing nikkud, and encoding into numbers.

I'm not entirely sure about the replacing end letters and converting to numbers.
Eventually I want to create json file that contains the possible characters with their corresponding ID in the values.
Any chance you already have such a json already?

Regarding the output, how can I convert it back to diactirized characters?

I successfully converted nakdimon.h5 to onnx runtime
https://github.com/thewh1teagle/nakdimon-ort

**Comment by elazarg** [comment]
> > I am not familiar with onnx, so I am not entirely sure I understand your question.
> > If you follow the code, you can see the preprocessing of the input - essentially chunking, replacing end-letters with normal ones, removing nikkud, and encoding into numbers.
> 
> I'm not entirely sure about the replacing end letters and converting to numbers. Eventually I want to create json file that contains the possible characters with their corresponding ID in the values. Any chance you already have such a json already?

The dictionaries in the [CharacterTables](https://github.com/elazarg/nakdimon/blob/master/nakdimon/dataset.py#L10-L34) should be easy to serialize as json.

> Regarding the output, how can I convert it back to diactirized characters?

You simply put each Nikkud character after the corresponding letter, if it is meaningful to that letter. Take a look at [merge_undonditional](https://github.com/elazarg/nakdimon/blob/master/nakdimon/predict.py#L23-L35) (`t` stands for text, i.e. a letter; `n` is the general Nikkud, `d` is Dagesh, `s` is Sin/Shin). 

> I successfully converted nakdimon.h5 to onnx runtime https://github.com/thewh1teagle/nakdimon-ort

Cool!

> I will be much easier to use nakdimon through onnxruntime as you only need one lightweight dependency, and you can then run it in every programming language / microcontroller / webassembly etc. Plus the model weight then is only 20MB

Sounds really good!

**Comment by thewh1teagle** [comment]
> You simply put each Nikkud character after the corresponding letter, if it is meaningful to that letter. Take a look at [merge_undonditional](https://github.com/elazarg/nakdimon/blob/master/nakdimon/predict.py#L23-L35) (`t` stands for text, i.e. a letter; `n` is the general Nikkud, `d` is Dagesh, `s` is Sin/Shin).

I created the file [config.json](https://github.com/thewh1teagle/nakdimon-ort/blob/main/config.json) which should hold everything related to input/output of nakdimon. Do you see something that is missing?

I still not fully understand how to push the input and get the output correctly. Added some of it in [infer.py](https://github.com/thewh1teagle/nakdimon-ort/blob/main/infer.py)
Could you write detailed pseudo code so I may understand better? I want to refactor the input/output processing to make it completely simple

**Comment by elazarg** [comment]
Does the dotter file help? It implements from scratch everything that's needed for prediction, but in JS.

https://github.com/elazarg/nakdimon/blob/master/web/dotter.js

**Comment by thewh1teagle** [comment]
> Does the dotter.js file help? It implements from scratch everything that's needed for prediction, but in JS.

Thanks! I didn't notice that file. it really helped.

It's much better now and I also published it. the only issue is that the tests failing in the assertion of the text although it looks the same

Did you experienced that issue? Maybe it has invisible characters?

_test folder_
https://github.com/thewh1teagle/nakdimon-ort/tree/main/test
_test run_
https://github.com/thewh1teagle/nakdimon-ort/actions/runs/10674015165/job/29583866366#step:6:35

**Comment by elazarg** [comment]
Looks like an of-by-one error - it reads the wrong index starting from the second chunk or something like that.

**Comment by thewh1teagle** [comment]
> Looks like an of-by-one error - it reads the wrong index starting from the second chunk or something like that.

I think that also the python version in this repo has the same issue that my tests are failed with, though the website of nakdimon looks ok.


```console
from nakdimon import diacritize
import sys

input = sys.argv[1]
output = sys.argv[2]

text = open(input, 'r', encoding='utf-8').read()
dotted_text = diacritize(text)
print(text == dotted_text)
print(text)
print(dotted_text)
with open(output, 'w', encoding='utf-8') as f:
    f.write(dotted_text)
```

```console
python main.py input.txt output.txt
```

_input:_

```console
אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב
```

_output_:

```console
אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אַבְ
```

Notice that last two.
My error in the tests is same: https://github.com/thewh1teagle/nakdimon-ort/actions/runs/10687274913/job/29624502628#step:6:53

**Comment by elazarg** [comment]
If the input contains a new line (as it should), this does not reproduce on my machine. Without the newline, the system thinks it a chunk that's broken mid-phrase, so it tries to guess the continuation ("אברהם", maybe?).

It makes sense to make `diacritize()` append a new line to the input and then remove it later. If that's indeed the issue.

**Comment by thewh1teagle** [comment]
> If the input contains a new line (as it should), this does not reproduce on my machine.

That's correct. When adding newline at the end this issue not present.
I still experience the old issue though, the input rows looks exactly the same but the output looks different

```console
אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב
```

This is ok

But adding one more produce invalid in the end 

```console
אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב אָב

```

Doesn't produce niqqud at the end sequence (` אב`)

 How can I debug it? the input tensor looks exactly the same. the output tensor looks similar but not exact at the beginning, in the middle / end it doesn't looks identical.

**Comment by elazarg** [comment]
Opened https://github.com/thewh1teagle/nakdimon-ort/pull/2. Seems to work, on the examples I tried.

**Comment by thewh1teagle** [comment]
> Opened [thewh1teagle/nakdimon-ort#2](https://github.com/thewh1teagle/nakdimon-ort/pull/2). Seems to work, on the examples I tried.

All the tests finally passed so I published 'stable' version of the library. 

Thank you!
